# only for cleaning

.PHONY: all
all:
	@echo Cheers

.PHONY: clean
clean:
	rm -f *~
	rm -f etc_0/*~
	rm -f etc_1/*~
	rm -f etc_2/*~
	rm -f etc_3/*~
	rm -f etc_4/*~
	rm -f etc_5/*~
	rm -f etc_6/*~
	rm -f etc_7/*~


distclean: clean
