.\" Manpage for a20_sdk
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH a20_sdk 7 "22 Jul 2016" "0.0.1" "a20_sdk man page"
.SH NAME
a20_sdk
\-\- the a20_sdk
.SH SYNOPSIS
.PP
.SH DESCRIPTION
This functions are part of the
.BR a20_sdk
(https://github.com/tjohann/a20_sdk.git)
.PP
The baalue daemon
.PP
.SH Directory(s)
.BR baalue.c
\- function implementation
.br
.BR baalue.h
\- interface header
.br
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR tbd.(1)
.PP
.BR tbd.(1)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP
